### ISSUE TITLE
Feature request: Toggle settings from a list

### ISSUE THREAD

**Issue by diogo-rossi** [ericbiewener/vscode-settings-on-fire#2]
Is it possible to define a "second level list" from which to select the setting?

Instead of "on" and "off", it could show a second list from which to select te settings.

An example of configuration would be:

```json
"settingsOnFire.toggle": {
    "Rulers": {
        "Ruler on 80": {
            "_label": "Cyan line",
            "editor.rulers": [
                {
                    "column": 79,
                    "color": "#4f717a"
                },
            ]
        },
        "Ruler on 85": {
            "_label": "Yellow line",
            "editor.rulers": [
                {
                    "column": 84,
                    "color": "#615f44"
                },
            ]
        },
        "Ruler on 95": {
            "_label": "Blue line",
            "editor.rulers": [
                {
                    "column": 94,
                    "color": "#00028a"
                },
            ]
        },
    },
    "Python launch args": {
        "No args": {
            "python.terminal.launchArgs": [
                ""
            ]
        },
        "IPython": {
            "python.terminal.launchArgs": [
                "-m",
                "IPython",
            ]
        },
        "Python interactive": {
            "python.terminal.launchArgs": [
                "-i"
            ]
        },
    },
},
```

### First list
![image](https://user-images.githubusercontent.com/57204023/187351249-1bd586e2-4529-4037-a0f5-103b3726196b.png)

### Second list (choosing the ruler setting)
![image](https://user-images.githubusercontent.com/57204023/187351454-73c6450e-fe47-49a1-85a2-3911872ad921.png)

**Comment by diogo-rossi** [comment]
I build a [new extension](https://github.com/Diogo-Rossi/vscode-settings-switcher) based on this one, making the requested modifications. I couldn't create a fork because I wasn't able to work with `yarn` (this was my first extension in VS Code), but I mention VScode Settings on Fire in the README. Thank you for making this extension!

**Comment by ericbiewener** [comment]
Nice job!
